import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const profiles = sqliteTable('profiles', { id: text().primaryKey(), name: text().notNull(), language: text().notNull().default('ko'), autoTranslate: integer('auto_translate').notNull().default(1), seen: integer().notNull() });
export const posts = sqliteTable('posts', { id: text().primaryKey(), author: text().notNull(), title: text().notNull(), body: text().notNull(), category: text().notNull(), tags: text().notNull(), language: text().notNull(), kind: text().notNull().default('post'), extra: text().notNull().default('{}'), forkOf: text('fork_of'), created: integer().notNull(), activity: integer().notNull(), views: integer().notNull().default(0), sample: integer().notNull().default(0) }, t => [index('posts_category_created').on(t.category, t.created), index('posts_kind_created').on(t.kind, t.created)]);
export const comments = sqliteTable('comments', { id: text().primaryKey(), postId: text('post_id').notNull().references(() => posts.id), author: text().notNull(), parentId: text('parent_id'), body: text().notNull(), language: text().notNull(), created: integer().notNull() }, t => [index('comments_post_created').on(t.postId, t.created)]);
export const votes = sqliteTable('votes', { postId: text('post_id').notNull().references(() => posts.id), userId: text('user_id').notNull(), value: integer().notNull(), created: integer().notNull() }, t => [primaryKey({ columns: [t.postId, t.userId] })]);
export const messages = sqliteTable('messages', { id: text().primaryKey(), author: text().notNull(), channel: text().notNull(), body: text().notNull(), language: text().notNull(), created: integer().notNull() }, t => [index('messages_channel_created').on(t.channel, t.created)]);
export const translations = sqliteTable('translations', { key: text().primaryKey(), body: text().notNull(), created: integer().notNull() });
export const views = sqliteTable('views', { postId: text('post_id').notNull(), viewer: text().notNull(), day: text().notNull() }, t => [primaryKey({ columns: [t.postId, t.viewer, t.day] })]);
export const limits = sqliteTable('limits', { key: text().primaryKey(), count: integer().notNull() });
